version: "3.8"

services:
  nestjs-backend:
    build: .
    container_name: gestaoparts-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/finances
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - gestaoparts-network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gestaoparts-network

volumes:
  mongo_data:
  node_modules:

networks:
  gestaoparts-network:
